_version: 1
gameplay-mechanics:
  arrow-movement-resets-despawn-counter: false
  entities-can-random-stroll-into-non-ticking-chunks: true
  entity-wake-up-duration-ratio-standard-deviation: 0.2
  fixes:
    broadcast-crit-animations-as-the-entity-being-critted: false
    mc-121706: true
    mc-238526: false
  try-respawn-ender-dragon-after-end-crystal-place: true
small-optimizations:
  load-chunks:
    to-activate-climbing-entities: false
    to-spawn-phantoms: false
  max-projectile-chunk-loads:
    per-projectile:
      max: 8
      remove-from-world-after-reach-limit: false
      reset-movement-after-reach-limit: false
    per-tick: 10
  reduced-intervals:
    acquire-poi-for-stuck-entity: 60
    check-stuck-in-wall: 10
    villager-item-repickup: 100
  save-fireworks: false
  use-optimized-sheep-offspring-color: true
