[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SourceSmpRoot,
    [string]$FrontierJarPath,
    [int]$BackendPort = 25568
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ServerRoot = $PSScriptRoot
$PluginsRoot = Join-Path $ServerRoot 'plugins'
$SourcePlugins = Join-Path $SourceSmpRoot 'plugins'

function Assert-Sha256 {
    param([string]$Path, [string]$Expected)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "Missing file: $Path" }
    $actual = (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actual -ne $Expected.ToLowerInvariant()) {
        throw "SHA-256 mismatch for $Path`nExpected: $Expected`nActual:   $actual"
    }
}

function Copy-Verified {
    param([string]$Source, [string]$Destination, [string]$Sha256)
    Assert-Sha256 $Source $Sha256
    New-Item -ItemType Directory -Path (Split-Path -Parent $Destination) -Force | Out-Null
    Copy-Item -LiteralPath $Source -Destination $Destination -Force
}

function Get-ChallengeArtifactHashes {
    $hashFile = Join-Path $ServerRoot 'PLUGIN-SHA256SUMS.txt'
    if (-not (Test-Path -LiteralPath $hashFile -PathType Leaf)) {
        throw "Missing workflow-generated challenge hash manifest: $hashFile"
    }
    $result = @{}
    foreach ($line in [System.IO.File]::ReadAllLines($hashFile)) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        if ($line -notmatch '^([0-9a-fA-F]{64})\s+(.+)$') {
            throw "Malformed challenge hash line: $line"
        }
        $name = [System.IO.Path]::GetFileName($Matches[2].Trim())
        $result[$name] = $Matches[1].ToLowerInvariant()
    }
    return $result
}

function Ensure-LeafRuntime {
    $jar = Join-Path $ServerRoot 'leaf-1.21.11-179.jar'
    $sha = '5da79782215c1a25edcd7c73b3523b7ecb7f4b86dc8a5846a176ed69bc2cd020'
    if (-not (Test-Path -LiteralPath $jar -PathType Leaf)) {
        $url = 'https://github.com/Winds-Studio/Leaf/releases/download/ver-1.21.11/leaf-1.21.11-179.jar'
        $tmp = "$jar.download"
        Write-Host 'Downloading verified Leaf 1.21.11 build 179...'
        Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $tmp
        Assert-Sha256 $tmp $sha
        Move-Item -LiteralPath $tmp -Destination $jar -Force
    }
    Assert-Sha256 $jar $sha
}

function Get-PaperVelocitySecret {
    param([string]$Path)
    $lines = [System.IO.File]::ReadAllLines($Path)
    $insideVelocity = $false
    $velocityIndent = -1
    foreach ($line in $lines) {
        if (-not $insideVelocity) {
            if ($line -match '^(\s*)velocity:\s*$') {
                $insideVelocity = $true
                $velocityIndent = $Matches[1].Length
            }
            continue
        }
        if ([string]::IsNullOrWhiteSpace($line) -or $line.TrimStart().StartsWith('#')) { continue }
        [void]($line -match '^(\s*)')
        $indent = $Matches[1].Length
        if ($indent -le $velocityIndent) { $insideVelocity = $false; continue }
        if ($line -match '^\s*secret:\s*(.+?)\s*$') {
            $secret = $Matches[1].Trim().Trim('"').Trim("'")
            if ([string]::IsNullOrWhiteSpace($secret) -or $secret -match '<REDACTED>|REPLACE_WITH') {
                throw 'Source Velocity forwarding secret is empty/redacted.'
            }
            return $secret
        }
    }
    throw "Could not find proxies.velocity.secret in $Path"
}

function Set-PaperVelocitySecret {
    param([string]$Path, [string]$Secret)
    $lines = [System.Collections.Generic.List[string]]::new()
    [System.IO.File]::ReadAllLines($Path) | ForEach-Object { [void]$lines.Add($_) }
    $insideVelocity = $false
    $velocityIndent = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if (-not $insideVelocity) {
            if ($line -match '^(\s*)velocity:\s*$') { $insideVelocity = $true; $velocityIndent = $Matches[1].Length }
            continue
        }
        if ([string]::IsNullOrWhiteSpace($line) -or $line.TrimStart().StartsWith('#')) { continue }
        [void]($line -match '^(\s*)')
        $indent = $Matches[1].Length
        if ($indent -le $velocityIndent) { break }
        if ($line -match '^(\s*)secret:\s*') {
            $lines[$i] = $Matches[1] + 'secret: "' + $Secret.Replace('"','\"') + '"'
            [System.IO.File]::WriteAllLines($Path, $lines)
            return
        }
    }
    throw "Could not replace proxies.velocity.secret in $Path"
}

# These four artifacts are built specifically for Frontier Test and are authoritative.
# Their exact hashes are generated by the same workflow that publishes the JARs.
$challengeArtifacts = Get-ChallengeArtifactHashes
$requiredChallengeArtifacts = @(
    'EnthusiaTempChallenges-0.2.0-frontier.1.jar',
    'EnthusiaAdvancements-1.0.0-frontier.jar',
    'UltimateAdvancementAPI-2.8.1.jar',
    'EnthusiaTags.jar'
)
foreach ($name in $requiredChallengeArtifacts) {
    if (-not $challengeArtifacts.ContainsKey($name)) {
        throw "Challenge hash manifest does not contain required artifact: $name"
    }
    Assert-Sha256 (Join-Path $PluginsRoot $name) $challengeArtifacts[$name]
}
if (-not (Test-Path -LiteralPath (Join-Path $PluginsRoot 'EnthusiaTags\config.yml') -PathType Leaf)) {
    throw 'Frontier-specific EnthusiaTags config is missing.'
}

# Copy only the regular network/server dependencies from SMP. Challenge artifacts above are excluded.
$copies = @(
    @{ S='CoreProtect-24.1.jar'; D='CoreProtect-24.1.jar'; H='a7137839a5b20d993e168381dee22136c4ca77979c9d5627ccbdb7c4058d737f' },
    @{ S='InventoryRollbackPlus-1.8.2.jar'; D='InventoryRollbackPlus-1.8.2.jar'; H='2caada5cd90e86767466dd67c5f1b9616adafdccfe561da44d84985e9ffac43d' },
    @{ S='EnthusiaPlaytime-3.7.2.jar'; D='EnthusiaPlaytime-3.7.2.jar'; H='d6d79b11588c9d60ece254798480e83b7c286b1909d138c803db11f6a1ec9344' },
    @{ S='LuckPerms-Bukkit-5.5.53.jar'; D='LuckPerms-Bukkit-5.5.53.jar'; H='fc8d4eccbf11c1e844af4527f018bbfde90c1866a9aba1bf880173a8e644cd59' },
    @{ S='floodgate-spigot.jar'; D='floodgate-spigot.jar'; H='21570aff9ce17d6983928e8552777760e1ede5050026b04c686b0ae112e6fd7e' },
    @{ S='BedrockWindChargeFix-1.0.0.jar'; D='BedrockWindChargeFix-1.0.0.jar'; H='ddd4583ed2b3ba9c90a8293936f4cb6ff8b990d4233646de6d80d91528155d8d' },
    @{ S='nexo-1.22.1.jar'; D='nexo-1.22.1.jar'; H='8771545bf1d29500641c29733a741f863eccbf7dbf43217691dee8de33d43bac' },
    @{ S='PlaceholderAPI-2.12.3.jar'; D='PlaceholderAPI-2.12.3.jar'; H='fde03259f5af6938f3c33eeb4d814000a1adabf1d2304ce14970be81f609a437' },
    @{ S='TAB v5.5.0.jar'; D='TAB-v5.5.0.jar'; H='829e7ec22bc41069d93b53479a8fe4a335a579c9c5b37a4cf140da176aea65f6' }
)
foreach ($item in $copies) {
    Copy-Verified (Join-Path $SourcePlugins $item.S) (Join-Path $PluginsRoot $item.D) $item.H
}

$frontierTarget = Join-Path $PluginsRoot 'EnthusiaFrontier-0.1.1.jar'
if (-not [string]::IsNullOrWhiteSpace($FrontierJarPath)) {
    Copy-Verified $FrontierJarPath $frontierTarget '74b90cafbd96cdbd9a51d07bc897b223161eab87bb7014416d662250442aeefa'
}
if (-not (Test-Path -LiteralPath $frontierTarget -PathType Leaf)) {
    throw 'EnthusiaFrontier-0.1.1.jar is missing. Use the branch-published runtime JAR or pass -FrontierJarPath.'
}
Assert-Sha256 $frontierTarget '74b90cafbd96cdbd9a51d07bc897b223161eab87bb7014416d662250442aeefa'

# Copy private Floodgate identity material locally; it remains gitignored.
$sourceFloodgateKey = Join-Path $SourcePlugins 'floodgate\key.pem'
if (-not (Test-Path -LiteralPath $sourceFloodgateKey -PathType Leaf)) { throw "Missing Floodgate key: $sourceFloodgateKey" }
Copy-Item -LiteralPath $sourceFloodgateKey -Destination (Join-Path $PluginsRoot 'floodgate\key.pem') -Force

# Use the live LuckPerms network DB configuration but force this backend's server context.
$sourceLuckPerms = Join-Path $SourcePlugins 'LuckPerms\config.yml'
if (-not (Test-Path -LiteralPath $sourceLuckPerms -PathType Leaf)) { throw "Missing LuckPerms config: $sourceLuckPerms" }
$lpText = [System.IO.File]::ReadAllText($sourceLuckPerms)
if ($lpText -match '<REDACTED>|REPLACE_WITH') { throw 'LuckPerms source config is sanitized; use a raw live SMP copy.' }
$lpText = [regex]::Replace($lpText, '(?m)^server:\s*.*$', 'server: EnthusiaFrontierTest', 1)
[System.IO.File]::WriteAllText((Join-Path $PluginsRoot 'LuckPerms\config.yml'), $lpText)

# Copy the full Nexo asset/config directory from the live server so emoji textures and pack assets exist.
$sourceNexo = Join-Path $SourcePlugins 'Nexo'
if (-not (Test-Path -LiteralPath $sourceNexo -PathType Container)) { throw "Missing Nexo directory: $sourceNexo" }
$sourceNexoSettings = Join-Path $sourceNexo 'settings.yml'
$nexoSettingsText = [System.IO.File]::ReadAllText($sourceNexoSettings)
if ($nexoSettingsText -match '<REDACTED>|REPLACE_WITH') { throw 'Nexo source settings are sanitized; use a raw live SMP copy.' }
$destNexo = Join-Path $PluginsRoot 'Nexo'
if (Test-Path -LiteralPath $destNexo) { Remove-Item -LiteralPath $destNexo -Recurse -Force }
Copy-Item -LiteralPath $sourceNexo -Destination $destNexo -Recurse -Force

# Reuse the network's modern forwarding secret without printing it.
$secret = Get-PaperVelocitySecret (Join-Path $SourceSmpRoot 'config\paper-global.yml')
Set-PaperVelocitySecret (Join-Path $ServerRoot 'config\paper-global.yml') $secret

# Apply the actual backend allocation.
$propertiesPath = Join-Path $ServerRoot 'server.properties'
$props = [System.IO.File]::ReadAllText($propertiesPath)
$props = [regex]::Replace($props, '(?m)^server-port=.*$', "server-port=$BackendPort")
$props = [regex]::Replace($props, '(?m)^query\.port=.*$', "query.port=$BackendPort")
[System.IO.File]::WriteAllText($propertiesPath, $props)

Ensure-LeafRuntime

Write-Host 'Frontier Test runtime populated from the live SMP files.' -ForegroundColor Green
Write-Host 'Frontier challenge/advancement/Tags artifacts were preserved and workflow-hash-verified.'
Write-Host 'Running final static runtime validation...'
& (Join-Path $ServerRoot 'validate-runtime.ps1')
